fpath=(~/.zsh/completion $fpath)

autoload -U compinit
compinit -C

for function in ~/.zsh/functions/*; do
  source $function
done

set -o emacs

bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word
bindkey -s "^T" "^Asudo ^E"

setopt auto_cd
setopt prompt_subst
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome
setopt correct
setopt correct_all
setopt extended_glob
setopt interactivecomments

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

unsetopt correct_all

export PS1='[${SSH_CONNECTION+"%n@%m:"}%~] '
export DIRSTACKSIZE=10

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

export PATH="/usr/local/bin:$PATH"

if which direnv > /dev/null; then eval "$(direnv hook zsh)"; fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export PATH=".git/safe/../../bin:$PATH"

[[ -s "${HOME}/.aliases" ]] && source "${HOME}/.aliases"
