fpath=(~/.zsh/completion $fpath)

autoload -U compinit
compinit -C

for function in ~/.zsh/functions/*; do
  source $function
done

set -o emacs

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt auto_cd
setopt autopushd
setopt correct
setopt correct_all
setopt extended_glob
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt interactivecomments
setopt prompt_subst
setopt pushdminus
setopt pushdsilent
setopt pushdtohome
setopt share_history

unsetopt correct_all

export PS1='[${SSH_CONNECTION+"%n@%m:"}%~] '
export DIRSTACKSIZE=10

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH=".git/safe/../../node_modules/.bin:$PATH"
export PATH=".git/safe/../../bin:$PATH"
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/Library/pnpm:$PATH"

[[ -s "${HOME}/.aliases" ]] && source "${HOME}/.aliases"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
